spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: case_mgmt
    password: password
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  flyway:
    clean-disabled: false

# Development specific logging
logging:
  level:
    com.mig.sales.api: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Pega Integration for Development
pega:
  integration:
    base-url: http://localhost:8080
    api-key: dev-api-key
    timeout: 10s
