spring:
  datasource:
    url: jdbc:oracle:thin:@${DB_HOST}:${DB_PORT}:${DB_SERVICE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
  
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  
  flyway:
    clean-disabled: true

# Production logging
logging:
  level:
    com.mig.sales.api: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
  file:
    name: /var/log/case-management-api/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Production Pega Integration
pega:
  integration:
    base-url: ${PEGA_BASE_URL}
    api-key: ${PEGA_API_KEY}
    timeout: 30s
    retry:
      max-attempts: 5
      delay: 2s

# Security
spring:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 3600000 # 1 hour for production
      refresh-expiration: 86400000 # 24 hours
