-- =====================================================================
-- Case Management API - Initial Schema Documentation
-- =====================================================================
-- This migration documents the existing schema from the legacy system
-- and adds audit columns for the new API system.

-- Create audit columns for existing tables
ALTER TABLE APP_USERS ADD (
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    UPDATED_BY VARCHAR2(50)
);

ALTER TABLE LEADS ADD (
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    UPDATED_BY VARCHAR2(50)
);

ALTER TABLE LEAD_HISTORY ADD (
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Add indexes for performance
CREATE INDEX IDX_LEADS_STATUS ON LEADS(STATUS);
CREATE INDEX IDX_LEADS_ASSIGNED_TO ON LEADS(ASSIGNED_TO);
CREATE INDEX IDX_LEADS_CREATED_DATE ON LEADS(CREATED_DATE);
CREATE INDEX IDX_LEAD_HISTORY_LEAD_ID ON LEAD_HISTORY(LEAD_ID);
CREATE INDEX IDX_LEAD_HISTORY_TIMESTAMP ON LEAD_HISTORY(TIMESTAMP);

-- Add comments for documentation
COMMENT ON TABLE APP_USERS IS 'Users table for authentication and authorization';
COMMENT ON TABLE LEADS IS 'Leads table for potential clients';
COMMENT ON TABLE LEAD_HISTORY IS 'Audit trail for lead activities';

COMMENT ON COLUMN APP_USERS.USER_ID IS 'Primary key for users';
COMMENT ON COLUMN APP_USERS.USERNAME IS 'Unique username for login';
COMMENT ON COLUMN APP_USERS.PASSWORD IS 'Hashed password';
COMMENT ON COLUMN APP_USERS.ROLE IS 'User role: SALES_PERSON or SALES_MANAGER';

COMMENT ON COLUMN LEADS.LEAD_ID IS 'Primary key for leads';
COMMENT ON COLUMN LEADS.LEAD_NAME IS 'Name of the lead';
COMMENT ON COLUMN LEADS.COMPANY IS 'Company name';
COMMENT ON COLUMN LEADS.EMAIL IS 'Email address';
COMMENT ON COLUMN LEADS.PHONE IS 'Phone number';
COMMENT ON COLUMN LEADS.STATUS IS 'Lead status: NEW, ASSIGNED, IN_PROGRESS, PRE_CONVERSION, CONVERTED, REJECTED';
COMMENT ON COLUMN LEADS.ASSIGNED_TO IS 'Foreign key to APP_USERS.USER_ID';
COMMENT ON COLUMN LEADS.POTENTIAL_VALUE IS 'Estimated value of the lead';
COMMENT ON COLUMN LEADS.LEAD_SOURCE IS 'Source of the lead';
COMMENT ON COLUMN LEADS.LEAD_SCORE IS 'Calculated score for the lead';

COMMENT ON COLUMN LEAD_HISTORY.HISTORY_ID IS 'Primary key for history records';
COMMENT ON COLUMN LEAD_HISTORY.LEAD_ID IS 'Foreign key to LEADS.LEAD_ID';
COMMENT ON COLUMN LEAD_HISTORY.USER_ID IS 'Foreign key to APP_USERS.USER_ID';
COMMENT ON COLUMN LEAD_HISTORY.COMMENT_TEXT IS 'Comment or description';
COMMENT ON COLUMN LEAD_HISTORY.ACTION IS 'Action performed';
COMMENT ON COLUMN LEAD_HISTORY.TIMESTAMP IS 'When the action occurred';
